plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
  - jekyll-seo-tag
markdown: kramdown
theme: minima
minima:
  skin: dark
relative_links:
  enabled: true
  collections: true
include:
  - README.md
